/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:88eb9c49-a389-44a4-a47a-b3a1f44cd732",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_U1WTtoD1k",
    "aws_user_pools_web_client_id": "5hn2uoeacaub0g8um1t993795c",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "socialmediabe52d728ca6c4c80b6f5f51dd962c20f173153-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
